version: '3.4'

services:
  lesson4:
    image: ${DOCKER_REGISTRY-}lesson4
    container_name: students.app
    build:
      context: .idea
      dockerfile: Dock
    depends_on:
      - students-db
  students-db:
    image: mysql:latest
    container_name: students.db
    environment:
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_DATABASE=SchoolDB
    volumes:
      - ./.containers/database:/var/lib/mysql
    ports:
      - 3306:3306